"""add and remove mutiple tables

Revision ID: 28675bb5e19b
Revises: 1a0abe8230dd
Create Date: 2026-06-25 04:54:04.625348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28675bb5e19b'
down_revision: Union[str, Sequence[str], None] = '1a0abe8230dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_teachers',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_teachers_class_id_classes'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_class_teachers_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_class_teachers_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_teachers')),
    sa.UniqueConstraint('teacher_id', 'class_id', name='uq_teacher_class')
    )
    op.create_index(op.f('ix_class_teachers_class_id'), 'class_teachers', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_teachers_school_id'), 'class_teachers', ['school_id'], unique=False)
    op.create_index(op.f('ix_class_teachers_teacher_id'), 'class_teachers', ['teacher_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_class_teachers_teacher_id'), table_name='class_teachers')
    op.drop_index(op.f('ix_class_teachers_school_id'), table_name='class_teachers')
    op.drop_index(op.f('ix_class_teachers_class_id'), table_name='class_teachers')
    op.drop_table('class_teachers')
    # ### end Alembic commands ###
