"""add unique constraint on school_id + username

Revision ID: 2fff45caf03a
Revises: 78909165fde7
Create Date: 2026-06-15 15:59:22.007976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fff45caf03a'
down_revision: Union[str, Sequence[str], None] = '78909165fde7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=255), nullable=True))
    op.create_unique_constraint('uq_school_username', 'users', ['school_id', 'username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_school_username', 'users', type_='unique')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
