"""add unique constraint on school_id + username

Revision ID: 3d794b3a742b
Revises: 2fff45caf03a
Create Date: 2026-06-16 12:25:44.124503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d794b3a742b'
down_revision: Union[str, Sequence[str], None] = '2fff45caf03a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('state', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'state')
    # ### end Alembic commands ###
