"""init

Revision ID: 423cf34fe59e
Revises: f07fc7c1e67e
Create Date: 2026-06-14 08:40:58.259723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '423cf34fe59e'
down_revision: Union[str, Sequence[str], None] = 'f07fc7c1e67e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timetables', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('timetables', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timetables', 'updated_at')
    op.drop_column('timetables', 'created_at')
    # ### end Alembic commands ###
