"""add and remove mutiple tables

Revision ID: 4d4976e36608
Revises: b1679069d052
Create Date: 2026-06-24 05:32:02.946859

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d4976e36608'
down_revision: Union[str, Sequence[str], None] = 'b1679069d052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_profiles_class_id'), table_name='student_profiles')
    op.drop_constraint(op.f('fk_student_profiles_class_id_classes'), 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'class_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_student_profiles_class_id_classes'), 'student_profiles', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_student_profiles_class_id'), 'student_profiles', ['class_id'], unique=False)
    # ### end Alembic commands ###
