"""add and remove mutiple tables

Revision ID: 6957859b84e9
Revises: 9fcd7ec86705
Create Date: 2026-06-21 11:23:08.084405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6957859b84e9'
down_revision: Union[str, Sequence[str], None] = '9fcd7ec86705'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_sessions',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_academic_sessions_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_academic_sessions'))
    )
    op.create_index(op.f('ix_academic_sessions_school_id'), 'academic_sessions', ['school_id'], unique=False)
    op.create_table('student_enrollments',
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_student_enrollments_class_id_classes')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_student_enrollments_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], name=op.f('fk_student_enrollments_session_id_academic_sessions')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_enrollments_student_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_enrollments')),
    sa.UniqueConstraint('student_id', 'session_id', name='uq_student_session_enrollment')
    )
    op.create_index(op.f('ix_student_enrollments_class_id'), 'student_enrollments', ['class_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_school_id'), 'student_enrollments', ['school_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_session_id'), 'student_enrollments', ['session_id'], unique=False)
    op.create_index(op.f('ix_student_enrollments_student_id'), 'student_enrollments', ['student_id'], unique=False)
    op.create_table('teacher_class_subjects',
    sa.Column('teacher_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_teacher_class_subjects_class_id_classes')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_teacher_class_subjects_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_teacher_class_subjects_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teacher_class_subjects_teacher_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_class_subjects')),
    sa.UniqueConstraint('teacher_id', 'class_id', 'subject_id', name='uq_teacher_class_subject')
    )
    op.create_index(op.f('ix_teacher_class_subjects_class_id'), 'teacher_class_subjects', ['class_id'], unique=False)
    op.create_index(op.f('ix_teacher_class_subjects_school_id'), 'teacher_class_subjects', ['school_id'], unique=False)
    op.create_index(op.f('ix_teacher_class_subjects_subject_id'), 'teacher_class_subjects', ['subject_id'], unique=False)
    op.create_index(op.f('ix_teacher_class_subjects_teacher_id'), 'teacher_class_subjects', ['teacher_id'], unique=False)
    op.create_table('terms',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_terms_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], name=op.f('fk_terms_session_id_academic_sessions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_terms'))
    )
    op.create_index(op.f('ix_terms_school_id'), 'terms', ['school_id'], unique=False)
    op.create_table('attendance_sheets',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('attendance_date', sa.Date(), nullable=False),
    sa.Column('marked_by', sa.UUID(), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_attendance_sheets_class_id_classes')),
    sa.ForeignKeyConstraint(['marked_by'], ['users.id'], name=op.f('fk_attendance_sheets_marked_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_attendance_sheets_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], name=op.f('fk_attendance_sheets_session_id_academic_sessions')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_attendance_sheets_term_id_terms')),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('fk_attendance_sheets_updated_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_sheets')),
    sa.UniqueConstraint('class_id', 'session_id', 'term_id', 'attendance_date', name='uq_attendance_sheet')
    )
    op.create_index(op.f('ix_attendance_sheets_attendance_date'), 'attendance_sheets', ['attendance_date'], unique=False)
    op.create_index(op.f('ix_attendance_sheets_class_id'), 'attendance_sheets', ['class_id'], unique=False)
    op.create_index(op.f('ix_attendance_sheets_school_id'), 'attendance_sheets', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_sheets_session_id'), 'attendance_sheets', ['session_id'], unique=False)
    op.create_index(op.f('ix_attendance_sheets_term_id'), 'attendance_sheets', ['term_id'], unique=False)
    op.create_table('lessons',
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('objectives', sa.Text(), nullable=True),
    sa.Column('file_url', sa.Text(), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_lessons_class_id_classes')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_lessons_created_by_users')),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], name=op.f('fk_lessons_session_id_academic_sessions')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_lessons_subject_id_subjects')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_lessons_term_id_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_lessons'))
    )
    op.create_table('result_batches',
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('term_id', sa.UUID(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('requires_review', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_result_batches_class_id_classes')),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_result_batches_created_by_users')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_result_batches_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['academic_sessions.id'], name=op.f('fk_result_batches_session_id_academic_sessions')),
    sa.ForeignKeyConstraint(['term_id'], ['terms.id'], name=op.f('fk_result_batches_term_id_terms')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_batches'))
    )
    op.create_index(op.f('ix_result_batches_class_id'), 'result_batches', ['class_id'], unique=False)
    op.create_index(op.f('ix_result_batches_school_id'), 'result_batches', ['school_id'], unique=False)
    op.create_index(op.f('ix_result_batches_session_id'), 'result_batches', ['session_id'], unique=False)
    op.create_index(op.f('ix_result_batches_term_id'), 'result_batches', ['term_id'], unique=False)
    op.create_table('attendance_records',
    sa.Column('sheet_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('PRESENT', 'ABSENT', 'LATE', name='attendancestatus'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_attendance_records_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sheet_id'], ['attendance_sheets.id'], name=op.f('fk_attendance_records_sheet_id_attendance_sheets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_attendance_records_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attendance_records'))
    )
    op.create_index(op.f('ix_attendance_records_school_id'), 'attendance_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_sheet_id'), 'attendance_records', ['sheet_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_student_id'), 'attendance_records', ['student_id'], unique=False)
    op.create_index('ix_attendance_student_sheet', 'attendance_records', ['student_id', 'sheet_id'], unique=False)
    op.create_table('result_approvals',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('action_by', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('action_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['action_by'], ['users.id'], name=op.f('fk_result_approvals_action_by_users')),
    sa.ForeignKeyConstraint(['batch_id'], ['result_batches.id'], name=op.f('fk_result_approvals_batch_id_result_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_result_approvals_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_approvals'))
    )
    op.create_index(op.f('ix_result_approvals_batch_id'), 'result_approvals', ['batch_id'], unique=False)
    op.create_index(op.f('ix_result_approvals_school_id'), 'result_approvals', ['school_id'], unique=False)
    op.create_table('result_records',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('ca_score', sa.Integer(), nullable=False),
    sa.Column('exam_score', sa.Integer(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('grade', sa.String(length=5), nullable=False),
    sa.Column('remark', sa.String(length=100), nullable=True),
    sa.Column('teacher_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['result_batches.id'], name=op.f('fk_result_records_batch_id_result_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_result_records_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_result_records_student_id_users')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_result_records_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_records')),
    sa.UniqueConstraint('batch_id', 'student_id', 'subject_id', name='uq_result_record')
    )
    op.create_index(op.f('ix_result_records_batch_id'), 'result_records', ['batch_id'], unique=False)
    op.create_index(op.f('ix_result_records_school_id'), 'result_records', ['school_id'], unique=False)
    op.create_index(op.f('ix_result_records_student_id'), 'result_records', ['student_id'], unique=False)
    op.create_index(op.f('ix_result_records_subject_id'), 'result_records', ['subject_id'], unique=False)
    op.create_table('result_summaries',
    sa.Column('batch_id', sa.UUID(), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=False),
    sa.Column('total_score', sa.Integer(), nullable=False),
    sa.Column('average_score', sa.Float(), nullable=False),
    sa.Column('subjects_offered', sa.Integer(), nullable=False),
    sa.Column('passed_subjects', sa.Integer(), nullable=False),
    sa.Column('failed_subjects', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('principal_comment', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['result_batches.id'], name=op.f('fk_result_summaries_batch_id_result_batches'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_result_summaries_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_result_summaries_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_result_summaries')),
    sa.UniqueConstraint('batch_id', 'student_id', name='uq_result_summary')
    )
    op.create_index(op.f('ix_result_summaries_batch_id'), 'result_summaries', ['batch_id'], unique=False)
    op.create_index(op.f('ix_result_summaries_school_id'), 'result_summaries', ['school_id'], unique=False)
    op.create_index(op.f('ix_result_summaries_student_id'), 'result_summaries', ['student_id'], unique=False)
    op.drop_table('teacher_classes')
    op.drop_table('student_classes')
    op.drop_index(op.f('ix_timetables_school_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_index(op.f('ix_invites_code'), table_name='invites')
    op.drop_table('invites')
    op.create_index(op.f('ix_class_subjects_class_id'), 'class_subjects', ['class_id'], unique=False)
    op.create_index(op.f('ix_class_subjects_subject_id'), 'class_subjects', ['subject_id'], unique=False)
    op.create_unique_constraint('uq_class_subject', 'class_subjects', ['class_id', 'subject_id'])
    op.drop_constraint(op.f('fk_class_subjects_class_id_classes'), 'class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('fk_class_subjects_subject_id_subjects'), 'class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_class_subjects_class_id_classes'), 'class_subjects', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_class_subjects_subject_id_subjects'), 'class_subjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('classes', 'level',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('student_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('student_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_student_profiles_admission_number'), 'student_profiles', type_='unique')
    op.create_index(op.f('ix_student_profiles_admission_number'), 'student_profiles', ['admission_number'], unique=True)
    op.drop_constraint(op.f('fk_student_profiles_class_id_classes'), 'student_profiles', type_='foreignkey')
    op.drop_column('student_profiles', 'class_id')
    op.add_column('teacher_profiles', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('teacher_profiles', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_constraint(op.f('uq_teacher_profiles_employee_id'), 'teacher_profiles', type_='unique')
    op.create_index(op.f('ix_teacher_profiles_employee_id'), 'teacher_profiles', ['employee_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teacher_profiles_employee_id'), table_name='teacher_profiles')
    op.create_unique_constraint(op.f('uq_teacher_profiles_employee_id'), 'teacher_profiles', ['employee_id'], postgresql_nulls_not_distinct=False)
    op.drop_column('teacher_profiles', 'updated_at')
    op.drop_column('teacher_profiles', 'created_at')
    op.add_column('student_profiles', sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_student_profiles_class_id_classes'), 'student_profiles', 'classes', ['class_id'], ['id'])
    op.drop_index(op.f('ix_student_profiles_admission_number'), table_name='student_profiles')
    op.create_unique_constraint(op.f('uq_student_profiles_admission_number'), 'student_profiles', ['admission_number'], postgresql_nulls_not_distinct=False)
    op.drop_column('student_profiles', 'updated_at')
    op.drop_column('student_profiles', 'created_at')
    op.alter_column('classes', 'level',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('classes', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('fk_class_subjects_subject_id_subjects'), 'class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('fk_class_subjects_class_id_classes'), 'class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_class_subjects_subject_id_subjects'), 'class_subjects', 'subjects', ['subject_id'], ['id'])
    op.create_foreign_key(op.f('fk_class_subjects_class_id_classes'), 'class_subjects', 'classes', ['class_id'], ['id'])
    op.drop_constraint('uq_class_subject', 'class_subjects', type_='unique')
    op.drop_index(op.f('ix_class_subjects_subject_id'), table_name='class_subjects')
    op.drop_index(op.f('ix_class_subjects_class_id'), table_name='class_subjects')
    op.create_table('invites',
    sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('code', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('is_used', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_invites_school_id_schools')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invites'))
    )
    op.create_index(op.f('ix_invites_code'), 'invites', ['code'], unique=True)
    op.create_table('timetables',
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('subject_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('day_of_week', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('school_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_timetables_class_id_classes')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_timetables_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_timetables_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_timetables_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetables'))
    )
    op.create_index(op.f('ix_timetables_school_id'), 'timetables', ['school_id'], unique=False)
    op.create_table('student_classes',
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_student_classes_class_id_classes')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_classes_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_classes'))
    )
    op.create_table('teacher_classes',
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('class_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_teacher_classes_class_id_classes')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teacher_classes_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_classes'))
    )
    op.drop_index(op.f('ix_result_summaries_student_id'), table_name='result_summaries')
    op.drop_index(op.f('ix_result_summaries_school_id'), table_name='result_summaries')
    op.drop_index(op.f('ix_result_summaries_batch_id'), table_name='result_summaries')
    op.drop_table('result_summaries')
    op.drop_index(op.f('ix_result_records_subject_id'), table_name='result_records')
    op.drop_index(op.f('ix_result_records_student_id'), table_name='result_records')
    op.drop_index(op.f('ix_result_records_school_id'), table_name='result_records')
    op.drop_index(op.f('ix_result_records_batch_id'), table_name='result_records')
    op.drop_table('result_records')
    op.drop_index(op.f('ix_result_approvals_school_id'), table_name='result_approvals')
    op.drop_index(op.f('ix_result_approvals_batch_id'), table_name='result_approvals')
    op.drop_table('result_approvals')
    op.drop_index('ix_attendance_student_sheet', table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_student_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_sheet_id'), table_name='attendance_records')
    op.drop_index(op.f('ix_attendance_records_school_id'), table_name='attendance_records')
    op.drop_table('attendance_records')
    op.drop_index(op.f('ix_result_batches_term_id'), table_name='result_batches')
    op.drop_index(op.f('ix_result_batches_session_id'), table_name='result_batches')
    op.drop_index(op.f('ix_result_batches_school_id'), table_name='result_batches')
    op.drop_index(op.f('ix_result_batches_class_id'), table_name='result_batches')
    op.drop_table('result_batches')
    op.drop_table('lessons')
    op.drop_index(op.f('ix_attendance_sheets_term_id'), table_name='attendance_sheets')
    op.drop_index(op.f('ix_attendance_sheets_session_id'), table_name='attendance_sheets')
    op.drop_index(op.f('ix_attendance_sheets_school_id'), table_name='attendance_sheets')
    op.drop_index(op.f('ix_attendance_sheets_class_id'), table_name='attendance_sheets')
    op.drop_index(op.f('ix_attendance_sheets_attendance_date'), table_name='attendance_sheets')
    op.drop_table('attendance_sheets')
    op.drop_index(op.f('ix_terms_school_id'), table_name='terms')
    op.drop_table('terms')
    op.drop_index(op.f('ix_teacher_class_subjects_teacher_id'), table_name='teacher_class_subjects')
    op.drop_index(op.f('ix_teacher_class_subjects_subject_id'), table_name='teacher_class_subjects')
    op.drop_index(op.f('ix_teacher_class_subjects_school_id'), table_name='teacher_class_subjects')
    op.drop_index(op.f('ix_teacher_class_subjects_class_id'), table_name='teacher_class_subjects')
    op.drop_table('teacher_class_subjects')
    op.drop_index(op.f('ix_student_enrollments_student_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_session_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_school_id'), table_name='student_enrollments')
    op.drop_index(op.f('ix_student_enrollments_class_id'), table_name='student_enrollments')
    op.drop_table('student_enrollments')
    op.drop_index(op.f('ix_academic_sessions_school_id'), table_name='academic_sessions')
    op.drop_table('academic_sessions')
    # ### end Alembic commands ###
