"""add unique constraint on school_id + username

Revision ID: 9fcd7ec86705
Revises: 3d794b3a742b
Create Date: 2026-06-16 12:36:01.934783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9fcd7ec86705'
down_revision: Union[str, Sequence[str], None] = '3d794b3a742b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schools', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('schools', sa.Column('contact_person', sa.String(length=255), nullable=True))
    op.add_column('schools', sa.Column('whatsapp_number', sa.String(length=50), nullable=True))
    op.add_column('schools', sa.Column('average_fee_range', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('population_range', sa.String(length=100), nullable=True))
    op.add_column('schools', sa.Column('referral_source', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schools', 'referral_source')
    op.drop_column('schools', 'population_range')
    op.drop_column('schools', 'average_fee_range')
    op.drop_column('schools', 'whatsapp_number')
    op.drop_column('schools', 'contact_person')
    op.drop_column('schools', 'description')
    # ### end Alembic commands ###
