"""add and remove mutiple tables

Revision ID: b1679069d052
Revises: e0f7ff6b2392
Create Date: 2026-06-22 04:16:46.662915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1679069d052'
down_revision: Union[str, Sequence[str], None] = 'e0f7ff6b2392'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teacher_class_subjects_subject_id_subjects'), 'teacher_class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('fk_teacher_class_subjects_class_id_classes'), 'teacher_class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teacher_class_subjects_class_id_classes'), 'teacher_class_subjects', 'classes', ['class_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('fk_teacher_class_subjects_subject_id_subjects'), 'teacher_class_subjects', 'subjects', ['subject_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_teacher_class_subjects_subject_id_subjects'), 'teacher_class_subjects', type_='foreignkey')
    op.drop_constraint(op.f('fk_teacher_class_subjects_class_id_classes'), 'teacher_class_subjects', type_='foreignkey')
    op.create_foreign_key(op.f('fk_teacher_class_subjects_class_id_classes'), 'teacher_class_subjects', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(op.f('fk_teacher_class_subjects_subject_id_subjects'), 'teacher_class_subjects', 'subjects', ['subject_id'], ['id'])
    # ### end Alembic commands ###
