"""init

Revision ID: bc95a8d3fa00
Revises: eb6d3e302d68
Create Date: 2026-06-12 11:30:33.079654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc95a8d3fa00'
down_revision: Union[str, Sequence[str], None] = 'eb6d3e302d68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('access_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'access_token')
    # ### end Alembic commands ###
