"""add class_id foreign key to studentsprofile

Revision ID: e0f7ff6b2392
Revises: 9efa73c1f26a
Create Date: 2026-06-21 13:57:36.049660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0f7ff6b2392'
down_revision: Union[str, Sequence[str], None] = '9efa73c1f26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_profiles', sa.Column('class_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_student_profiles_class_id'), 'student_profiles', ['class_id'], unique=False)
    op.create_foreign_key(op.f('fk_student_profiles_class_id_classes'), 'student_profiles', 'classes', ['class_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_student_profiles_class_id_classes'), 'student_profiles', type_='foreignkey')
    op.drop_index(op.f('ix_student_profiles_class_id'), table_name='student_profiles')
    op.drop_column('student_profiles', 'class_id')
    # ### end Alembic commands ###
