"""init

Revision ID: eb6d3e302d68
Revises: 4cd5209464d4
Create Date: 2026-06-12 08:49:58.664527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb6d3e302d68'
down_revision: Union[str, Sequence[str], None] = '4cd5209464d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('parent_profiles', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('student_profiles', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('teacher_profiles', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('users', 'school_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('teacher_profiles', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('student_profiles', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('parent_profiles', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('classes', 'school_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
