"""init

Revision ID: f07fc7c1e67e
Revises: d4b6ecdbd25f
Create Date: 2026-06-14 06:11:06.322132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f07fc7c1e67e'
down_revision: Union[str, Sequence[str], None] = 'd4b6ecdbd25f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subjects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_subjects_school_id_schools'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subjects'))
    )
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_table('class_subjects',
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_class_subjects_class_id_classes')),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_class_subjects_subject_id_subjects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_class_subjects'))
    )
    op.create_table('student_classes',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_student_classes_class_id_classes')),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name=op.f('fk_student_classes_student_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_classes'))
    )
    op.create_table('teacher_classes',
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_teacher_classes_class_id_classes')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_teacher_classes_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_teacher_classes'))
    )
    op.create_table('timetables',
    sa.Column('class_id', sa.UUID(), nullable=True),
    sa.Column('subject_id', sa.UUID(), nullable=True),
    sa.Column('teacher_id', sa.UUID(), nullable=True),
    sa.Column('day_of_week', sa.String(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('school_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name=op.f('fk_timetables_class_id_classes')),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], name=op.f('fk_timetables_school_id_schools'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], name=op.f('fk_timetables_subject_id_subjects')),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name=op.f('fk_timetables_teacher_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_timetables'))
    )
    op.create_index(op.f('ix_timetables_school_id'), 'timetables', ['school_id'], unique=False)
    op.create_table('student_parents',
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('relationship', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['parent_profiles.id'], name=op.f('fk_student_parents_parent_id_parent_profiles')),
    sa.ForeignKeyConstraint(['student_id'], ['student_profiles.id'], name=op.f('fk_student_parents_student_id_student_profiles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_student_parents'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_parents')
    op.drop_index(op.f('ix_timetables_school_id'), table_name='timetables')
    op.drop_table('timetables')
    op.drop_table('teacher_classes')
    op.drop_table('student_classes')
    op.drop_table('class_subjects')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_table('subjects')
    # ### end Alembic commands ###
